# Generated by Django 3.2.7 on 2022-01-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Xbarr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xbarr_nkaryawan', models.IntegerField()),
                ('xbarr_npart', models.IntegerField()),
                ('xbarr_ntrial', models.IntegerField()),
                ('xbarr_stdev', models.IntegerField()),
                ('xbarr_stdevmax', models.IntegerField()),
                ('xbarr_stdevmin', models.IntegerField()),
            ],
        ),
    ]
