# Generated by Django 3.2.7 on 2022-01-29 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_all',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
    ]
