# Generated by Django 3.2.7 on 2022-02-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0002_xbarr_xbarr_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_karyawan',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='xbarr',
            name='xbarr_all',
            field=models.JSONField(null=True),
        ),
    ]
