# Generated by Django 3.2.7 on 2022-02-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0003_auto_20220202_0707'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_dba',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_dbs',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_dotline',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_resume',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_resumeg',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_rva',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_xva',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
