# Generated by Django 3.2.7 on 2022-02-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0004_auto_20220202_0727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey_date_project', models.DateField()),
                ('survey_data', models.TextField()),
                ('survey_cust_name', models.TextField()),
                ('survey_att_prod_unit', models.TextField()),
                ('survey_var_bias_working', models.TextField()),
                ('survey_part_name', models.TextField()),
                ('survey_att_qty', models.TextField()),
                ('survey_var_bias_over', models.TextField()),
                ('survey_part_number', models.TextField()),
                ('survey_var_variation', models.TextField()),
                ('survey_character', models.TextField()),
                ('survey_name', models.TextField()),
                ('survey_var_part_sample', models.TextField()),
                ('survey_category', models.TextField()),
                ('survey_sn', models.TextField()),
                ('survey_var_homogen', models.TextField()),
                ('survey_process_name', models.TextField()),
                ('survey_resolution', models.TextField()),
                ('survey_var_subgroup', models.TextField()),
                ('survey_symbol', models.TextField()),
                ('survey_unit', models.TextField()),
                ('survey_ref', models.TextField()),
                ('survey_next_cal', models.DateField()),
                ('survey_range_max', models.TextField()),
                ('survey_range_min', models.TextField()),
                ('survey_fmea', models.TextField()),
                ('survey_control_plan', models.TextField()),
            ],
        ),
    ]
