# Generated by Django 3.2.7 on 2022-02-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0005_survey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='survey_att_prod_unit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_att_qty',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_var_bias_over',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_var_bias_working',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_var_homogen',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_var_part_sample',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_var_subgroup',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='survey',
            name='survey_var_variation',
            field=models.TextField(null=True),
        ),
    ]
