# Generated by Django 3.2.7 on 2022-02-15 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0006_auto_20220213_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xbarr',
            name='xbarr_dba',
        ),
        migrations.RemoveField(
            model_name='xbarr',
            name='xbarr_dbs',
        ),
        migrations.RemoveField(
            model_name='xbarr',
            name='xbarr_dotline',
        ),
        migrations.RemoveField(
            model_name='xbarr',
            name='xbarr_resumeg',
        ),
        migrations.RemoveField(
            model_name='xbarr',
            name='xbarr_rva',
        ),
        migrations.RemoveField(
            model_name='xbarr',
            name='xbarr_xva',
        ),
    ]
