# Generated by Django 3.2.7 on 2022-02-15 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0007_auto_20220215_0353'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_study',
            field=models.JSONField(null=True),
        ),
    ]
