# Generated by Django 3.2.7 on 2022-02-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0008_survey_survey_study'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_att_cat',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_var_review',
            field=models.TextField(null=True),
        ),
    ]
