# Generated by Django 3.2.7 on 2022-02-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0009_auto_20220216_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_actual',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_plan',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='survey',
            name='survey_var_ave',
            field=models.TextField(null=True),
        ),
    ]
