# Generated by Django 3.2.7 on 2022-02-17 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0010_auto_20220216_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_survey_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
