# Generated by Django 3.2.7 on 2022-02-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0011_xbarr_xbarr_survey_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cross',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cross_survey_id', models.IntegerField()),
                ('cross_nkaryawan', models.IntegerField()),
                ('cross_npart', models.IntegerField()),
                ('cross_ntrial', models.IntegerField()),
                ('cross_stdev', models.IntegerField()),
                ('cross_stdevmax', models.IntegerField()),
                ('cross_stdevmin', models.IntegerField()),
                ('cross_karyawan', models.JSONField(null=True)),
                ('cross_all', models.JSONField(null=True)),
                ('cross_resume', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Linearity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linearity_survey_id', models.IntegerField()),
                ('linearity_npart', models.IntegerField()),
                ('linearity_nmeasurement', models.IntegerField()),
                ('linearity_confidence', models.IntegerField()),
                ('linearity_working_max', models.IntegerField()),
                ('linearity_working_min', models.IntegerField()),
                ('linearity_ref', models.TextField()),
                ('linearity_master', models.JSONField(null=True)),
                ('linearity_all', models.JSONField(null=True)),
            ],
        ),
    ]
