# Generated by Django 3.2.7 on 2022-02-21 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0012_cross_linearity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xbarr',
            name='xbarr_stdev',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='xbarr',
            name='xbarr_stdevmax',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='xbarr',
            name='xbarr_stdevmin',
            field=models.IntegerField(null=True),
        ),
    ]
