# Generated by Django 3.2.7 on 2022-02-23 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0013_auto_20220221_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_aabp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_dba',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_dbs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_psvc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_rva',
            field=models.TextField(null=True),
        ),
    ]
