# Generated by Django 3.2.7 on 2022-02-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0014_auto_20220223_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_recommendation',
            field=models.JSONField(null=True),
        ),
    ]
