# Generated by Django 3.2.7 on 2022-02-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0015_xbarr_xbarr_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='xbarr',
            name='xbarr_xva',
            field=models.TextField(null=True),
        ),
    ]
