# Generated by Django 3.2.7 on 2022-03-01 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0016_xbarr_xbarr_xva'),
    ]

    operations = [
        migrations.AddField(
            model_name='cross',
            name='cross_aabp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cross',
            name='cross_dba',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cross',
            name='cross_dbs',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cross',
            name='cross_psvc',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cross',
            name='cross_recommendation',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='cross',
            name='cross_rva',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cross',
            name='cross_xva',
            field=models.TextField(null=True),
        ),
    ]
