# Generated by Django 3.2.7 on 2022-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0017_auto_20220301_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearity',
            name='linearity_average',
            field=models.JSONField(null=True),
        ),
    ]
