# Generated by Django 3.2.7 on 2022-03-07 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0018_linearity_linearity_average'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearity',
            name='linearity_biasref',
            field=models.TextField(null=True),
        ),
    ]
