# Generated by Django 3.2.7 on 2022-03-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0019_linearity_linearity_biasref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cross',
            name='cross_stdev',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cross',
            name='cross_stdevmax',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='cross',
            name='cross_stdevmin',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='linearity',
            name='linearity_confidence',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='linearity',
            name='linearity_working_max',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='linearity',
            name='linearity_working_min',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='xbarr',
            name='xbarr_stdev',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='xbarr',
            name='xbarr_stdevmax',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='xbarr',
            name='xbarr_stdevmin',
            field=models.FloatField(null=True),
        ),
    ]
