# Generated by Django 3.2.7 on 2022-03-07 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0020_auto_20220307_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearity',
            name='linearity_recommendation',
            field=models.JSONField(null=True),
        ),
    ]
