# Generated by Django 3.2.7 on 2022-03-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0021_linearity_linearity_recommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_username', models.TextField()),
                ('user_password', models.TextField()),
                ('user_role', models.TextField()),
            ],
        ),
    ]
