# Generated by Django 3.2.7 on 2022-03-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0023_nested'),
    ]

    operations = [
        migrations.AddField(
            model_name='linearity',
            name='linearity_ave_measured',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linearity',
            name='linearity_ave_res',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linearity',
            name='linearity_ave_reviewed',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linearity',
            name='linearity_ave_sn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linearity',
            name='linearity_measured',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='linearity',
            name='linearity_reviewed',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
