# Generated by Django 3.2.7 on 2022-04-01 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0025_alter_linearity_linearity_recommendation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_company',
            field=models.TextField(default='PT.XXX'),
            preserve_default=False,
        ),
    ]
