# Generated by Django 3.2.7 on 2022-04-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0026_user_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='survey_user_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
