# Generated by Django 3.2.7 on 2022-04-04 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0027_survey_survey_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linearity',
            name='linearity_ave_reviewed',
        ),
    ]
