# Generated by Django 3.2.7 on 2022-05-19 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0029_vxbarr'),
    ]

    operations = [
        migrations.AddField(
            model_name='vxbarr',
            name='vxbarr_capability',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vxbarr',
            name='vxbarr_stability',
            field=models.TextField(null=True),
        ),
    ]
