# Generated by Django 3.2.7 on 2022-05-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0030_auto_20220519_0725'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sbarr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sbarr_survey_id', models.IntegerField()),
                ('sbarr_lsl', models.IntegerField()),
                ('sbarr_usl', models.IntegerField()),
                ('sbarr_subgroup', models.IntegerField()),
                ('sbarr_unit', models.TextField()),
                ('sbarr_all', models.JSONField(null=True)),
                ('sbarr_measured', models.TextField()),
                ('sbarr_reviewed', models.TextField()),
                ('sbarr_stability', models.TextField(null=True)),
                ('sbarr_capability', models.TextField(null=True)),
            ],
        ),
    ]
