# Generated by Django 3.2.7 on 2022-06-01 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0031_sbarr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imr_survey_id', models.IntegerField()),
                ('imr_lsl', models.IntegerField()),
                ('imr_usl', models.IntegerField()),
                ('imr_subgroup', models.IntegerField()),
                ('imr_all', models.JSONField(null=True)),
                ('imr_measured', models.TextField()),
                ('imr_reviewed', models.TextField()),
                ('imr_stability', models.TextField(null=True)),
                ('imr_capability', models.TextField(null=True)),
            ],
        ),
    ]
