# Generated by Django 3.2.7 on 2022-06-07 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0032_imr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pchart_survey_id', models.IntegerField()),
                ('pchart_sample', models.IntegerField()),
                ('pchart_freq', models.IntegerField()),
                ('pchart_all', models.JSONField(null=True)),
                ('pchart_defect', models.TextField()),
                ('pchart_reviewed', models.TextField()),
                ('pchart_reason', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='imr',
            name='imr_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sbarr',
            name='sbarr_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='vxbarr',
            name='vxbarr_reason',
            field=models.TextField(null=True),
        ),
    ]
