# Generated by Django 3.2.7 on 2022-06-08 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0033_auto_20220607_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pchart',
            name='pchart_defect',
            field=models.JSONField(null=True),
        ),
    ]
