# Generated by Django 3.2.7 on 2022-06-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0034_alter_pchart_pchart_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='pchart',
            name='pchart_measured',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
