# Generated by Django 3.2.7 on 2022-06-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0035_pchart_pchart_measured'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cchart_survey_id', models.IntegerField()),
                ('cchart_sample', models.IntegerField()),
                ('cchart_freq', models.IntegerField()),
                ('cchart_all', models.JSONField(null=True)),
                ('cchart_defect', models.JSONField(null=True)),
                ('cchart_measured', models.TextField()),
                ('cchart_reviewed', models.TextField()),
                ('cchart_reason', models.TextField(null=True)),
                ('cchart_recommendation', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Npchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npchart_survey_id', models.IntegerField()),
                ('npchart_sample', models.IntegerField()),
                ('npchart_freq', models.IntegerField()),
                ('npchart_all', models.JSONField(null=True)),
                ('npchart_defect', models.JSONField(null=True)),
                ('npchart_measured', models.TextField()),
                ('npchart_reviewed', models.TextField()),
                ('npchart_reason', models.TextField(null=True)),
                ('npchart_recommendation', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Uchart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uchart_survey_id', models.IntegerField()),
                ('uchart_sample', models.IntegerField()),
                ('uchart_freq', models.IntegerField()),
                ('uchart_all', models.JSONField(null=True)),
                ('uchart_defect', models.JSONField(null=True)),
                ('uchart_measured', models.TextField()),
                ('uchart_reviewed', models.TextField()),
                ('uchart_reason', models.TextField(null=True)),
                ('uchart_recommendation', models.JSONField(null=True)),
            ],
        ),
    ]
