# Generated by Django 3.2.7 on 2022-06-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0036_cchart_npchart_uchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cchart',
            name='cchart_class',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='npchart',
            name='npchart_class',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pchart',
            name='pchart_class',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uchart',
            name='uchart_class',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
