# Generated by Django 3.2.7 on 2022-06-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0037_auto_20220614_0359'),
    ]

    operations = [
        migrations.AddField(
            model_name='uchart',
            name='uchart_nsample',
            field=models.JSONField(null=True),
        ),
    ]
