# Generated by Django 3.2.7 on 2022-06-29 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0038_uchart_uchart_nsample'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stability_survey_id', models.IntegerField()),
                ('stability_sample', models.IntegerField()),
                ('stability_all', models.JSONField(null=True)),
                ('stability_measured', models.TextField()),
                ('stability_reviewed', models.TextField()),
                ('stability_reference', models.TextField()),
                ('stability_stable', models.TextField()),
                ('stability_gauge', models.TextField()),
            ],
        ),
    ]
