# Generated by Django 3.2.7 on 2022-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0039_stability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kappa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kappa_survey_id', models.IntegerField()),
                ('kappa_nkaryawan', models.IntegerField()),
                ('kappa_npart', models.IntegerField()),
                ('kappa_ntrial', models.IntegerField()),
                ('kappa_karyawan', models.JSONField(null=True)),
                ('kappa_all', models.JSONField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kendall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kendall_survey_id', models.IntegerField()),
                ('kendall_nkaryawan', models.IntegerField()),
                ('kendall_npart', models.IntegerField()),
                ('kendall_ntrial', models.IntegerField()),
                ('kendall_karyawan', models.JSONField(null=True)),
                ('kendall_all', models.JSONField(null=True)),
            ],
        ),
    ]
