# Generated by Django 3.2.7 on 2022-07-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0040_kappa_kendall'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medianr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medianr_survey_id', models.IntegerField()),
                ('medianr_subgroup', models.IntegerField()),
                ('medianr_unit', models.TextField()),
                ('medianr_all', models.JSONField(null=True)),
                ('medianr_measured', models.TextField()),
                ('medianr_reviewed', models.TextField()),
                ('medianr_reason', models.TextField(null=True)),
            ],
        ),
    ]
