# Generated by Django 3.2.7 on 2022-07-30 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0041_medianr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medianr',
            name='medianr_unit',
        ),
        migrations.AddField(
            model_name='medianr',
            name='medianr_lsl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medianr',
            name='medianr_usl',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
