# Generated by Django 3.2.7 on 2022-08-06 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0042_auto_20220730_0902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bias_survey_id', models.IntegerField()),
                ('bias_ntrial', models.IntegerField()),
                ('bias_master', models.IntegerField()),
                ('bias_date', models.DateField(null=True)),
                ('bias_res', models.FloatField()),
                ('bias_sn', models.TextField(null=True)),
                ('bias_room', models.TextField(null=True)),
                ('bias_ngauge', models.IntegerField()),
                ('bias_average', models.JSONField(null=True)),
                ('bias_all', models.JSONField(null=True)),
                ('bias_check', models.JSONField(null=True)),
                ('bias_recommendation', models.TextField(null=True)),
                ('bias_reviewed', models.TextField()),
                ('bias_measured', models.TextField()),
            ],
        ),
    ]
