# Generated by Django 3.2.7 on 2022-08-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0043_bias'),
    ]

    operations = [
        migrations.AddField(
            model_name='bias',
            name='bias_ref',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
