# Generated by Django 3.2.7 on 2022-08-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0044_bias_bias_ref'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bias',
            name='bias_master',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bias',
            name='bias_ntrial',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='bias',
            name='bias_res',
            field=models.FloatField(null=True),
        ),
    ]
