# Generated by Django 3.2.7 on 2022-08-13 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0045_auto_20220806_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='bias',
            name='bias_ave_measured',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
