# Generated by Django 3.2.7 on 2022-08-13 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0046_bias_bias_ave_measured'),
    ]

    operations = [
        migrations.AddField(
            model_name='bias',
            name='bias_method',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
