# Generated by Django 3.2.7 on 2022-08-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0048_resolusi'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_category',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_character',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_cpn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_customer',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_fmea',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_measurement',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_next_cal',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_part_info',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_part_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_part_number',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_process_name',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_project_date',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_range_max',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_range_min',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_sn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_symbol',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_user_id',
            field=models.TextField(null=True),
        ),
    ]
