# Generated by Django 3.2.7 on 2022-09-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0049_auto_20220828_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_reason',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resolusi',
            name='resolusi_study_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resolusi',
            name='resolusi_project_date',
            field=models.DateField(null=True),
        ),
    ]
