# Generated by Django 3.2.7 on 2023-03-25 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coretoolcrud', '0050_auto_20220901_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_islogin',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
